import { RolPrecio } from '@prisma/client';
import { CreateNewProductDto } from '../dto/create-productNew.dto';
const ROL_PUBLICO = RolPrecio.PUBLICO;

export const itemsBase /* : CreateNewProductDto[] */ = [
  // ===================== ABARROTERÍA (10) =====================
  {
    codigoProducto: 'GT-ABR-0001',
    codigoProveedor: 'PROV-AB-0001',
    nombre: 'Arroz blanco 1 kg',
    descripcion: 'Grano seleccionado, ideal para mesa diaria.',
    precioCostoActual: 9.5,
    precioVenta: [{ precio: '13.00', orden: 1, rol: ROL_PUBLICO }],
    categorias: [],
    presentaciones: [],
    stockMinimo: 20,
  },
  {
    codigoProducto: 'GT-ABR-0002',
    codigoProveedor: 'PROV-AB-0002',
    nombre: 'Frijol negro 1 lb',
    descripcion: 'Cosecha nacional, grano limpio.',
    precioCostoActual: 7.2,
    precioVenta: [{ precio: '10.50', orden: 1, rol: ROL_PUBLICO }],
    categorias: [],
    presentaciones: [],
    stockMinimo: 18,
  },
  {
    codigoProducto: 'GT-ABR-0003',
    codigoProveedor: 'PROV-AB-0003',
    nombre: 'Azúcar blanca 1 kg',
    descripcion: 'Refinada, dulce uniforme.',
    precioCostoActual: 6.8,
    precioVenta: [{ precio: '9.50', orden: 1, rol: ROL_PUBLICO }],
    categorias: [],
    presentaciones: [],
    stockMinimo: 16,
  },
  {
    codigoProducto: 'GT-ABR-0004',
    codigoProveedor: 'PROV-AB-0004',
    nombre: 'Aceite vegetal 1 L',
    descripcion: 'Aceite comestible para freír y cocinar.',
    precioCostoActual: 15.5,
    precioVenta: [{ precio: '21.00', orden: 1, rol: ROL_PUBLICO }],
    categorias: [],
    presentaciones: [],
    stockMinimo: 14,
  },
  {
    codigoProducto: 'GT-ABR-0005',
    codigoProveedor: 'PROV-AB-0005',
    nombre: 'Sal yodada 1 lb',
    descripcion: 'Con yodo para la salud.',
    precioCostoActual: 2.3,
    precioVenta: [{ precio: '4.00', orden: 1, rol: ROL_PUBLICO }],
    categorias: [],
    presentaciones: [],
    stockMinimo: 20,
  },
  {
    codigoProducto: 'GT-ABR-0006',
    codigoProveedor: 'PROV-AB-0006',
    nombre: 'Harina de maíz 1 kg',
    descripcion: 'Para tortillas y tamalitos.',
    precioCostoActual: 6.2,
    precioVenta: [{ precio: '9.00', orden: 1, rol: ROL_PUBLICO }],
    categorias: [],
    presentaciones: [],
    stockMinimo: 18,
  },
  {
    codigoProducto: 'GT-ABR-0007',
    codigoProveedor: 'PROV-AB-0007',
    nombre: 'Café molido 250 g',
    descripcion: 'Tueste medio, aroma intenso.',
    precioCostoActual: 18.0,
    precioVenta: [{ precio: '25.00', orden: 1, rol: ROL_PUBLICO }],
    categorias: [],
    presentaciones: [],
    stockMinimo: 10,
  },
  {
    codigoProducto: 'GT-ABR-0008',
    codigoProveedor: 'PROV-AB-0008',
    nombre: 'Leche entera UHT 1 L',
    descripcion: 'Leche ultrapasteurizada.',
    precioCostoActual: 10.8,
    precioVenta: [{ precio: '14.50', orden: 1, rol: ROL_PUBLICO }],
    categorias: [],
    presentaciones: [],
    stockMinimo: 12,
  },
  {
    codigoProducto: 'GT-ABR-0009',
    codigoProveedor: 'PROV-AB-0009',
    nombre: 'Galletas maría 6 paquetes',
    descripcion: 'Paquete familiar crujiente.',
    precioCostoActual: 12.0,
    precioVenta: [{ precio: '16.50', orden: 1, rol: ROL_PUBLICO }],
    categorias: [],
    presentaciones: [],
    stockMinimo: 14,
  },
  {
    codigoProducto: 'GT-ABR-0010',
    codigoProveedor: 'PROV-AB-0010',
    nombre: 'Atún en agua 142 g',
    descripcion: 'Listo para ensaladas y sándwich.',
    precioCostoActual: 8.2,
    precioVenta: [{ precio: '11.50', orden: 1, rol: ROL_PUBLICO }],
    categorias: [],
    presentaciones: [],
    stockMinimo: 16,
  },

  // ===================== FERRETERÍA (10) =====================
  {
    codigoProducto: 'GT-FER-0001',
    codigoProveedor: 'PROV-FE-0001',
    nombre: 'Martillo carpintero 16 oz',
    descripcion: 'Mango de fibra, cabezal pulido.',
    precioCostoActual: 38.0,
    precioVenta: [{ precio: '55.00', orden: 1, rol: ROL_PUBLICO }],
    categorias: [],
    presentaciones: [],
    stockMinimo: 6,
  },
  {
    codigoProducto: 'GT-FER-0002',
    codigoProveedor: 'PROV-FE-0002',
    nombre: 'Destornillador plano 6"',
    descripcion: 'Punta magnética, agarre ergonómico.',
    precioCostoActual: 12.0,
    precioVenta: [{ precio: '18.00', orden: 1, rol: ROL_PUBLICO }],
    categorias: [],
    presentaciones: [],
    stockMinimo: 10,
  },
  {
    codigoProducto: 'GT-FER-0003',
    codigoProveedor: 'PROV-FE-0003',
    nombre: 'Cinta métrica 5 m',
    descripcion: 'Cinta reforzada con freno.',
    precioCostoActual: 22.0,
    precioVenta: [{ precio: '30.00', orden: 1, rol: ROL_PUBLICO }],
    categorias: [],
    presentaciones: [],
    stockMinimo: 8,
  },
  {
    codigoProducto: 'GT-FER-0004',
    codigoProveedor: 'PROV-FE-0004',
    nombre: 'Alicate universal 8"',
    descripcion: 'Acero al carbono, aislado.',
    precioCostoActual: 28.0,
    precioVenta: [{ precio: '39.00', orden: 1, rol: ROL_PUBLICO }],
    categorias: [],
    presentaciones: [],
    stockMinimo: 8,
  },
  {
    codigoProducto: 'GT-FER-0005',
    codigoProveedor: 'PROV-FE-0005',
    nombre: 'Serrucho 20"',
    descripcion: 'Dientes templados para corte rápido.',
    precioCostoActual: 35.0,
    precioVenta: [{ precio: '49.00', orden: 1, rol: ROL_PUBLICO }],
    categorias: [],
    presentaciones: [],
    stockMinimo: 5,
  },
  {
    codigoProducto: 'GT-FER-0006',
    codigoProveedor: 'PROV-FE-0006',
    nombre: 'Pala cuadrada',
    descripcion: 'Mango de madera dura.',
    precioCostoActual: 60.0,
    precioVenta: [{ precio: '82.00', orden: 1, rol: ROL_PUBLICO }],
    categorias: [],
    presentaciones: [],
    stockMinimo: 4,
  },
  {
    codigoProducto: 'GT-FER-0007',
    codigoProveedor: 'PROV-FE-0007',
    nombre: 'Flexómetro 8 m',
    descripcion: 'Carcasa antiimpacto, clip metálico.',
    precioCostoActual: 30.0,
    precioVenta: [{ precio: '42.00', orden: 1, rol: ROL_PUBLICO }],
    categorias: [],
    presentaciones: [],
    stockMinimo: 6,
  },
  {
    codigoProducto: 'GT-FER-0008',
    codigoProveedor: 'PROV-FE-0008',
    nombre: 'Llave ajustable 10"',
    descripcion: 'Ajuste fino, escala grabada.',
    precioCostoActual: 40.0,
    precioVenta: [{ precio: '58.00', orden: 1, rol: ROL_PUBLICO }],
    categorias: [],
    presentaciones: [],
    stockMinimo: 6,
  },
  {
    codigoProducto: 'GT-FER-0009',
    codigoProveedor: 'PROV-FE-0009',
    nombre: 'Cúter metálico',
    descripcion: 'Cuerpo robusto, cuchilla retráctil.',
    precioCostoActual: 10.0,
    precioVenta: [{ precio: '15.00', orden: 1, rol: ROL_PUBLICO }],
    categorias: [],
    presentaciones: [],
    stockMinimo: 12,
  },
  {
    codigoProducto: 'GT-FER-0010',
    codigoProveedor: 'PROV-FE-0010',
    nombre: 'Brocha 2"',
    descripcion: 'Cerdas sintéticas, mango plástico.',
    precioCostoActual: 8.0,
    precioVenta: [{ precio: '12.00', orden: 1, rol: ROL_PUBLICO }],
    categorias: [],
    presentaciones: [],
    stockMinimo: 14,
  },

  // ===================== FARMACIA (10) =====================
  {
    codigoProducto: 'GT-FAR-0001',
    codigoProveedor: 'PROV-FA-0001',
    nombre: 'Paracetamol 500 mg (blíster 10)',
    descripcion: 'Analgésico y antipirético.',
    precioCostoActual: 6.5,
    precioVenta: [{ precio: '9.50', orden: 1, rol: ROL_PUBLICO }],
    categorias: [],
    presentaciones: [],
    stockMinimo: 24,
  },
  {
    codigoProducto: 'GT-FAR-0002',
    codigoProveedor: 'PROV-FA-0002',
    nombre: 'Ibuprofeno 400 mg (blíster 10)',
    descripcion: 'Antiinflamatorio no esteroideo.',
    precioCostoActual: 8.0,
    precioVenta: [{ precio: '12.00', orden: 1, rol: ROL_PUBLICO }],
    categorias: [],
    presentaciones: [],
    stockMinimo: 20,
  },
  {
    codigoProducto: 'GT-FAR-0003',
    codigoProveedor: 'PROV-FA-0003',
    nombre: 'Loratadina 10 mg (blíster 10)',
    descripcion: 'Antihistamínico para alergias.',
    precioCostoActual: 7.0,
    precioVenta: [{ precio: '10.50', orden: 1, rol: ROL_PUBLICO }],
    categorias: [],
    presentaciones: [],
    stockMinimo: 18,
  },
  {
    codigoProducto: 'GT-FAR-0004',
    codigoProveedor: 'PROV-FA-0004',
    nombre: 'Vitamina C 500 mg (blíster 10)',
    descripcion: 'Soporte inmunológico.',
    precioCostoActual: 6.0,
    precioVenta: [{ precio: '9.00', orden: 1, rol: ROL_PUBLICO }],
    categorias: [],
    presentaciones: [],
    stockMinimo: 20,
  },
  {
    codigoProducto: 'GT-FAR-0005',
    codigoProveedor: 'PROV-FA-0005',
    nombre: 'Alcohol en gel 250 ml',
    descripcion: 'Higiene de manos al instante.',
    precioCostoActual: 9.0,
    precioVenta: [{ precio: '13.00', orden: 1, rol: ROL_PUBLICO }],
    categorias: [],
    presentaciones: [],
    stockMinimo: 16,
  },
  {
    codigoProducto: 'GT-FAR-0006',
    codigoProveedor: 'PROV-FA-0006',
    nombre: 'Gasas estériles (paquete 10)',
    descripcion: 'Curas y primeros auxilios.',
    precioCostoActual: 8.5,
    precioVenta: [{ precio: '12.50', orden: 1, rol: ROL_PUBLICO }],
    categorias: [],
    presentaciones: [],
    stockMinimo: 12,
  },
  {
    codigoProducto: 'GT-FAR-0007',
    codigoProveedor: 'PROV-FA-0007',
    nombre: 'Vendas elásticas 10 cm',
    descripcion: 'Soporte y compresión.',
    precioCostoActual: 10.0,
    precioVenta: [{ precio: '14.50', orden: 1, rol: ROL_PUBLICO }],
    categorias: [],
    presentaciones: [],
    stockMinimo: 10,
  },
  {
    codigoProducto: 'GT-FAR-0008',
    codigoProveedor: 'PROV-FA-0008',
    nombre: 'Agua oxigenada 120 ml',
    descripcion: 'Antiséptico tópico.',
    precioCostoActual: 5.5,
    precioVenta: [{ precio: '8.00', orden: 1, rol: ROL_PUBLICO }],
    categorias: [],
    presentaciones: [],
    stockMinimo: 14,
  },
  {
    codigoProducto: 'GT-FAR-0009',
    codigoProveedor: 'PROV-FA-0009',
    nombre: 'Ungüento antibiótico 15 g',
    descripcion: 'Cuidado de heridas menores.',
    precioCostoActual: 16.0,
    precioVenta: [{ precio: '22.00', orden: 1, rol: ROL_PUBLICO }],
    categorias: [],
    presentaciones: [],
    stockMinimo: 8,
  },
  {
    codigoProducto: 'GT-FAR-0010',
    codigoProveedor: 'PROV-FA-0010',
    nombre: 'Termómetro digital',
    descripcion: 'Lectura rápida y precisa.',
    precioCostoActual: 35.0,
    precioVenta: [{ precio: '48.00', orden: 1, rol: ROL_PUBLICO }],
    categorias: [],
    presentaciones: [],
    stockMinimo: 6,
  },

  // ===================== SURTIDOS / TIENDA (10) =====================
  {
    codigoProducto: 'GT-SUR-0001',
    codigoProveedor: 'PROV-SU-0001',
    nombre: 'Refresco cola 2.5 L',
    descripcion: 'Bebida gaseosa familiar.',
    precioCostoActual: 15.0,
    precioVenta: [{ precio: '21.00', orden: 1, rol: ROL_PUBLICO }],
    categorias: [],
    presentaciones: [],
    stockMinimo: 12,
  },
  {
    codigoProducto: 'GT-SUR-0002',
    codigoProveedor: 'PROV-SU-0002',
    nombre: 'Huevo blanco docena',
    descripcion: 'Fresco, tamaño mediano.',
    precioCostoActual: 19.0,
    precioVenta: [{ precio: '26.00', orden: 1, rol: ROL_PUBLICO }],
    categorias: [],
    presentaciones: [],
    stockMinimo: 10,
  },
  {
    codigoProducto: 'GT-SUR-0003',
    codigoProveedor: 'PROV-SU-0003',
    nombre: 'Pan molde blanco 680 g',
    descripcion: 'Rebanadas suaves.',
    precioCostoActual: 16.0,
    precioVenta: [{ precio: '22.00', orden: 1, rol: ROL_PUBLICO }],
    categorias: [],
    presentaciones: [],
    stockMinimo: 10,
  },
  {
    codigoProducto: 'GT-SUR-0004',
    codigoProveedor: 'PROV-SU-0004',
    nombre: 'Margarina 227 g',
    descripcion: 'Para untar y cocinar.',
    precioCostoActual: 8.5,
    precioVenta: [{ precio: '12.00', orden: 1, rol: ROL_PUBLICO }],
    categorias: [],
    presentaciones: [],
    stockMinimo: 12,
  },
  {
    codigoProducto: 'GT-SUR-0005',
    codigoProveedor: 'PROV-SU-0005',
    nombre: 'Sardinas en salsa 155 g',
    descripcion: 'Ricas en proteína.',
    precioCostoActual: 6.0,
    precioVenta: [{ precio: '9.00', orden: 1, rol: ROL_PUBLICO }],
    categorias: [],
    presentaciones: [],
    stockMinimo: 14,
  },
  {
    codigoProducto: 'GT-SUR-0006',
    codigoProveedor: 'PROV-SU-0006',
    nombre: 'Mayonesa 445 g',
    descripcion: 'Sabor casero.',
    precioCostoActual: 17.0,
    precioVenta: [{ precio: '23.50', orden: 1, rol: ROL_PUBLICO }],
    categorias: [],
    presentaciones: [],
    stockMinimo: 10,
  },
  {
    codigoProducto: 'GT-SUR-0007',
    codigoProveedor: 'PROV-SU-0007',
    nombre: 'Salsa de tomate 400 g',
    descripcion: 'Ideal para pastas y guisos.',
    precioCostoActual: 6.0,
    precioVenta: [{ precio: '8.50', orden: 1, rol: ROL_PUBLICO }],
    categorias: [],
    presentaciones: [],
    stockMinimo: 16,
  },
  {
    codigoProducto: 'GT-SUR-0008',
    codigoProveedor: 'PROV-SU-0008',
    nombre: 'Cereal de maíz 300 g',
    descripcion: 'Crujiente, listo para desayuno.',
    precioCostoActual: 12.0,
    precioVenta: [{ precio: '17.00', orden: 1, rol: ROL_PUBLICO }],
    categorias: [],
    presentaciones: [],
    stockMinimo: 12,
  },
  {
    codigoProducto: 'GT-SUR-0009',
    codigoProveedor: 'PROV-SU-0009',
    nombre: 'Soda agua mineral 1 L',
    descripcion: 'Gasificada, refrescante.',
    precioCostoActual: 6.5,
    precioVenta: [{ precio: '9.50', orden: 1, rol: ROL_PUBLICO }],
    categorias: [],
    presentaciones: [],
    stockMinimo: 12,
  },
  {
    codigoProducto: 'GT-SUR-0010',
    codigoProveedor: 'PROV-SU-0010',
    nombre: 'Churros bolsa 100 g',
    descripcion: 'Snack salado.',
    precioCostoActual: 4.0,
    precioVenta: [{ precio: '6.00', orden: 1, rol: ROL_PUBLICO }],
    categorias: [],
    presentaciones: [],
    stockMinimo: 18,
  },

  // ===================== HOGAR / LIMPIEZA (10 extras) =====================
  {
    codigoProducto: 'GT-HOG-0001',
    codigoProveedor: 'PROV-HO-0001',
    nombre: 'Detergente en polvo 1 kg',
    descripcion: 'Removedor de manchas.',
    precioCostoActual: 16.0,
    precioVenta: [{ precio: '22.00', orden: 1, rol: ROL_PUBLICO }],
    categorias: [],
    presentaciones: [],
    stockMinimo: 12,
  },
  {
    codigoProducto: 'GT-HOG-0002',
    codigoProveedor: 'PROV-HO-0002',
    nombre: 'Suavizante 1 L',
    descripcion: 'Ropa suave y perfumada.',
    precioCostoActual: 14.0,
    precioVenta: [{ precio: '19.50', orden: 1, rol: ROL_PUBLICO }],
    categorias: [],
    presentaciones: [],
    stockMinimo: 10,
  },
  {
    codigoProducto: 'GT-HOG-0003',
    codigoProveedor: 'PROV-HO-0003',
    nombre: 'Lavaplatos líquido 750 ml',
    descripcion: 'Desengrasa y rinde.',
    precioCostoActual: 10.0,
    precioVenta: [{ precio: '14.00', orden: 1, rol: ROL_PUBLICO }],
    categorias: [],
    presentaciones: [],
    stockMinimo: 12,
  },
  {
    codigoProducto: 'GT-HOG-0004',
    codigoProveedor: 'PROV-HO-0004',
    nombre: 'Cloro 1 galón',
    descripcion: 'Desinfección profunda.',
    precioCostoActual: 12.5,
    precioVenta: [{ precio: '17.50', orden: 1, rol: ROL_PUBLICO }],
    categorias: [],
    presentaciones: [],
    stockMinimo: 10,
  },
  {
    codigoProducto: 'GT-HOG-0005',
    codigoProveedor: 'PROV-HO-0005',
    nombre: 'Jabón de barra 200 g',
    descripcion: 'Uso personal diario.',
    precioCostoActual: 4.2,
    precioVenta: [{ precio: '6.00', orden: 1, rol: ROL_PUBLICO }],
    categorias: [],
    presentaciones: [],
    stockMinimo: 20,
  },
  {
    codigoProducto: 'GT-HOG-0006',
    codigoProveedor: 'PROV-HO-0006',
    nombre: 'Papel higiénico (4 rollos)',
    descripcion: 'Suave y absorbente.',
    precioCostoActual: 12.0,
    precioVenta: [{ precio: '16.50', orden: 1, rol: ROL_PUBLICO }],
    categorias: [],
    presentaciones: [],
    stockMinimo: 16,
  },
  {
    codigoProducto: 'GT-HOG-0007',
    codigoProveedor: 'PROV-HO-0007',
    nombre: 'Toallas de cocina (rollo)',
    descripcion: 'Multiusos, alta absorción.',
    precioCostoActual: 9.0,
    precioVenta: [{ precio: '12.50', orden: 1, rol: ROL_PUBLICO }],
    categorias: [],
    presentaciones: [],
    stockMinimo: 14,
  },
  {
    codigoProducto: 'GT-HOG-0008',
    codigoProveedor: 'PROV-HO-0008',
    nombre: 'Fósforos (caja 10)',
    descripcion: 'Encendido fácil y seguro.',
    precioCostoActual: 5.0,
    precioVenta: [{ precio: '7.50', orden: 1, rol: ROL_PUBLICO }],
    categorias: [],
    presentaciones: [],
    stockMinimo: 18,
  },
  {
    codigoProducto: 'GT-HOG-0009',
    codigoProveedor: 'PROV-HO-0009',
    nombre: 'Bolsas para basura 30 L (10)',
    descripcion: 'Resistentes y prácticas.',
    precioCostoActual: 8.5,
    precioVenta: [{ precio: '12.00', orden: 1, rol: ROL_PUBLICO }],
    categorias: [],
    presentaciones: [],
    stockMinimo: 16,
  },
  {
    codigoProducto: 'GT-HOG-0010',
    codigoProveedor: 'PROV-HO-0010',
    nombre: 'Escoba plástica',
    descripcion: 'Cerdas durables, mango largo.',
    precioCostoActual: 18.0,
    precioVenta: [{ precio: '25.00', orden: 1, rol: ROL_PUBLICO }],
    categorias: [],
    presentaciones: [],
    stockMinimo: 8,
  },
];

const report: Array<{
  codigoProducto: string;
  status: 'created' | 'skipped' | 'error';
  error?: string;
}> = [];
